#+TITLE: Oh My Emacs GUI
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[https://github.com/xiaohanyu/oh-my-emacs][oh-my-emacs]].

* Basic GUI Settings
#+NAME: gui-basics
#+BEGIN_SRC emacs-lisp
  ;; believe me, you don't need menubar, toolbar nor scrollbar
  (dolist (mode '(menu-bar-mode tool-bar-mode scroll-bar-mode))
    (when (fboundp mode) (funcall mode -1)))

  ;; show column number and line number
  (dolist (mode '(column-number-mode line-number-mode global-linum-mode))
    (when (fboundp mode) (funcall mode t)))

  ;; make the fringe thinner (default is 8 in pixels)
  (fringe-mode 4)

  ;; show parenthesis match
  (show-paren-mode 1)
  (setq show-paren-style 'expression)
#+END_SRC

* Choose Monaco as the Default English Font
  :PROPERTIES:
  :CUSTOM_ID: font
  :END:

Choosing a good and comfortable font is quite important in your whole coding
life. Although the default font of emacs is good enough, I believe there're
better choices. And you can refer to [[http://hivelogic.com/articles/top-10-programming-fonts][TOP 10 PROGRAMMING FONTS]] and [[http://www.sitepoint.com/top-10-programming-fonts/][10 of the
Best Programming Fonts]] to get some feel of various programming fonts.

And I prefer [[http://en.wikipedia.org/wiki/Monaco_(typeface)][Monaco]]. However, I've googled a lot to prove that Monaco is free
to use on non-Mac platforms, but found nothing about the official warrant. So
I pretend that it is free. If you found any illegal issues, please tell me and
I'll choose another free font. Thanks.

Finally, about how to install Monaco fonts in Linux, see
https://github.com/cstrap/monaco-font. If you didn't install Monaco,
oh-my-emacs will fallback to the default font. Yeah, the so-called
self-adapting.

#+NAME: font
#+BEGIN_SRC emacs-lisp
  ;; frame font
  ;; Setting English Font
  (if (member "Monaco" (font-family-list))
      (set-face-attribute
       'default nil :font "Monaco 12"))
#+END_SRC

* Solarized Color Theme
  :PROPERTIES:
  :CUSTOM_ID: color-theme
  :END:

[[http://ethanschoonover.com/solarized][Solarized]] is my favourite color theme. it is available for multiple
applications, not only for emacs. I'll set this as the default theme for
oh-my-emacs.
#+NAME: color-theme
#+BEGIN_SRC emacs-lisp
  (add-to-list 'el-get-sources
               '(:name color-theme-solarized
                       :after (progn
                                (load-theme 'solarized-dark t))))
#+END_SRC

* Powerline
  :PROPERTIES:
  :CUSTOM_ID: powerline
  :END:

Powerline is an eye candy for emacs [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Mode-Line.html][mode line]]. Actually, the [[https://github.com/jonathanchu/emacs-powerline][emacs powerline]] is
inspired by [[https://github.com/Lokaltog/vim-powerline][vim-powerline]]. There're also powerline variants for [[https://github.com/erikw/tmux-powerline][tmux]], [[https://github.com/milkbikis/powerline-shell][shell]], etc.

#+NAME: powerline
#+BEGIN_SRC emacs-lisp
  (add-to-list 'el-get-sources
               '(:name powerline
                       :after (progn
                                (require 'powerline))))
#+END_SRC
