#+TITLE: Oh My Emacs Advanced
#+OPTIONS: toc:2 num:nil ^:nil

This is part of the [[https://github.com/xiaohanyu/oh-my-emacs][oh-my-emacs]].

This file contains some settings for =cc-mode=.

* Basic CC-Mode Settings
  :PROPERTIES:
  :CUSTOM_ID: basic-cc
  :END:

=cc-mode= is not a single mode, actually, =cc-mode= is a collection of emacs
major mode for "editing files containing C, C++, Objective-C, Java, CORBA IDL
(and the variants CORBA PSDL and CIDL), Pike and AWK code."

Although =cc-mode= is a bit old, it is still powerful and flexible. It
contains a powerful [[http://www.gnu.org/software/emacs/manual/html_mono/ccmode.html#Indentation-Engine-Basics][indentation engine]], supports various builtin coding
[[http://www.gnu.org/software/emacs/manual/html_mono/ccmode.html#Styles][styles]], and provides various useful [[http://www.gnu.org/software/emacs/manual/html_mono/ccmode.html#Minor-Modes][minor modes]].

You do need some basic elisp knowledge to master the power of =cc-mode=. For
example, you need to know what the difference between =setq= and
=setq-default=, some basic knowledge about elisp hooks, etc.

#+NAME: basic
#+BEGIN_SRC emacs-lisp
  (setq c-default-style '((java-mode . "java")
                          (awk-mode . "awk")
                          (c-mode . "k&r")
                          (c++-mode . "stroustrup")
                          (other . "linux")))

  (setq-default c-basic-offset 4)

  (defun ome-c-initialization-hook ()
    (define-key c-mode-base-map (kbd "RET") 'c-context-line-break))

  (add-hook 'c-initialization-hook 'ome-c-initialization-hook)

  (defun ome-c-mode-common-hook ()
    (add-to-list 'c-cleanup-list 'defun-close-semi)
    (c-toggle-hungry-state)
    (c-toggle-auto-newline)
    (subword-mode 1))

  ;; this will affect all modes derived from cc-mode, like
  ;; java-mode, php-mode, etc
  (add-hook 'c-mode-common-hook 'ome-c-mode-common-hook)
#+END_SRC

* Makefile Settings
  :PROPERTIES:
  :CUSTOM_ID: makefile
  :END:

The only thing you need to do in =makefile-mode= is to enable tab indentation
instead of space indentation, since =makefile-mode= relys on tabs being tabs
instead of a mixture of spaces and tabs, which I think, is a bug, but used as
a feature of makefile. Ah, weird details and historial dirty quirks of
makefile.

#+NAME: makefile
#+BEGIN_SRC emacs-lisp
  (add-hook 'makefile-mode-hook 'indent-tabs-mode)
#+END_SRC

* CMake
  :PROPERTIES:
  :CUSTOM_ID: cmake
  :END:

[[http://www.cmake.org/][CMake]] is my favourate build tool for C/C++ software. To be precise, CMake is
not a build tool, since it does not build the project, instead, it generates
the files needed by your build tool(GNU make, Visual Studio, etc). The only
thing that I dislike about CMake is its syntax, which is weird and hard to
type. Anyway, it is much better than conventional [[http://en.wikipedia.org/wiki/GNU_build_system][Autotools]], IMHO, Autotools is
quite complicated, brings more problems than it solves. Do not use it unless
you have to.

#+NAME: cmake
#+BEGIN_SRC emacs-lisp
  (add-to-list 'el-get-sources
               '(:name cmake-mode))
#+END_SRC

* Documentation with Doxymacs
  :PROPERTIES:
  :CUSTOM_ID: doxymacs
  :END:

#+BEGIN_QUOTE
Doxygen is the de facto standard tool for generating documentation from
annotated C++ sources, but it also supports other popular programming languages
such as C, Objective-C, C#, PHP, Java, Python, IDL (Corba, Microsoft, and
UNO/OpenOffice flavors), Fortran, VHDL, Tcl, and to some extent D.

-- http://www.doxygen.org/
#+END_QUOTE

[[http://doxymacs.sourceforge.net/][Doxymacs]] brings the power of doxygen to Emacs, you can easily insert Doxygen
style comments in emacs. The default keybindings are:
- =C-c d ?= look up documentation for the symbol under the point.
- =C-c d r= rescan your Doxygen tags file.
- =C-c d f= insert a Doxygen comment for the next function.
- =C-c d i= insert a Doxygen comment for the current file.
- =C-c d ;= insert a Doxygen comment for a member variable on the current line
  (like M-;).
- =C-c d m= insert a blank multi-line Doxygen comment.
- =C-c d s= insert a blank single-line Doxygen comment.
- =C-c d @= insert grouping comments around the current region.

If you like, you can even integrate Doxygen to CMake workflow, see [[http://majewsky.wordpress.com/2010/08/14/tip-of-the-day-cmake-and-doxygen/][here]].

#+NAME: doxymacs
#+BEGIN_SRC emacs-lisp
  (add-to-list 'el-get-sources
               '(:name doxymacs
                       :after (progn
                                (add-hook 'c-mode-common-hook 'doxymacs-mode)
                                (add-hook 'c-mode-common-hook 'doxymacs-font-lock))))
#+END_SRC
